# 配置MySQL数据库的连接参数
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_1?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: zzr_1
      password: 1234
   jpa:
      # 自动生成数据库的表
      generate-ddl: true
      properties:
         # 设置一个方言，用于自动加上MySQL的引擎名称，默认MyISAM不支持事务，不推荐使用。
         hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
   
   # 配置Redis的连接信息
   redis:
      # 这里换自己的IP
      host: 120.78.125.208
      port: 6379
      database: 15

   

# 修改运行时的端口号，因为一个端口号只能被一个人使用。
# 如果多个人使用一台服务器，自然要使用不同的端口！
server.port: 8078
